nqubits: 8
state: "DMatrix"
layer: 30
etime: True
# Optimization
optimization:
  status: True
  algorithm: "SLSQP"
  iteration: 1
  constraint: False
# Circuit config
circuit:
  draw: False
  ansatztype: "xy"
  time:
    min: 0.0
    max: 10.0
  coefficients:
    cn: 1.0
    bn: 0.0
    r: 0.0
  noise:
    status: True
    value: [0.0001, 0.0001, 0.0001, 0.0001]  # Noise probabilities for [r, cz, u, y] gates. Example: [0.0001, 0.0001, 0.0001, 0]
    factor: [0, 0, 0] # Noise identity factors for [r, u, y] gates
  param: "random"