nqubits: 8
state: "DMatrix"
layer: 25
etime: True
# Optimization
optimization:
  status: True
  algorithm: "SLSQP"
  iteration: 1
  constraint: False
# Circuit config
circuit:
  draw: False # Draw the circuit
  ansatztype: "xy"
  time:
    min: 0.0
    max: 10.0
  coefficients:
    cn: 1.0
    bn: 0.0
    r: 0.0
  noise:
    status: False
    value: [0.0001, 0.0001, 0.0001, 0.0001]  # Noise probabilities for [r, cz, u, y] gates.
    factor: [0, 0, 0] # Noise identity factors for [r, u, y] gates
  param: "random"