nqubits: 5
state: "DMatrix"
layer: 10
iteration: 1
optimizer: "SLSQP"
constraint: False
etime: True
output: 
# Circuit config
circuit:
  draw: False
  ansatztype: "xy"
  time:
    ti: 0
    tf: 10
  coefficients:
    cn: 1
    bn: 1
    r: 0
  noise:
    status: False
    value: 0.0001
    factor: 0
  param: "random"
