nqubits: 4
layer: 2
iteration: 1
optimizer: "SLSQP"
constraint: False
etime: True
# Circuit config
circuit:
  draw: True
  ansatztype: xy
  time:
    ti: 0
    tf: 10
  coefficients:
    cn: 1
    bn: 1
    r: 0
  noise:
    status: True
    value: 0.001
    factor: 0
  param: "random"
  